name: ci

on:
  push:
    branches:
    - dev
    - main
    tags:
    - v*
    paths-ignore:
    - LICENSE
    - '**.md'
  pull_request:
    branches:
    - dev
    - main
    paths-ignore:
    - LICENSE
    - '**.md'

jobs:
  build:

    name: "Build & package"
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Package
      run: dotnet pack --configuration Release --include-symbols
      env:
        MINVERBUILDMETADATA: ${GITHUB_RUN_NUMBER}

    - name: Publish package artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: FormFlow.nupkg
        path: src/FormFlow/bin/Release/*.nupkg


  release:

    name: "Release"
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: FormFlow.nupkg

    - name: Publish package to NuGet
      run: dotnet nuget push **/*.nupkg --api-key $NUGET_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
